Repository IMAP-Science-Operations-Center/imap-data-access, pull requests merged in 2025-02, with the labels that each got.

#113 MNT: Fix PyPI build error and update repoint folder to match it's filename
  .github/workflows/release.yml
  imap_data_access/file_validation.py
  tests/test_file_validation.py
Labels: enhancement

#124 Fixed some small bugs in ancillary file validation step
  imap_data_access/__init__.py
  imap_data_access/file_validation.py
  tests/test_file_validation.py
Labels: bug

#126 API demo notebook updates for Feb 2025 STM
  examples/api_demo.ipynb
Labels: documentation
